### ISSUE TITLE
feat: create ending part

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#10]
## What is this issue? 🚀
Implement two scene of ending.

## TODO 🏃‍♀️
- [x] make game over scene
- [x] create Cinemachine for game over scene
- [x] make game clear scene
- [x] apply game credit in game clear scene
- [x] create Cinemachine for game clear scene
