### ISSUE TITLE
feat: implement subgame of cafe tycoon

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#11]
## What is this issue? 🚀
create new mini-games: when customers order tiramisu cake.

## TODO 🏃‍♀️
- [ ] implement mini-game
- [ ] apply it into main game
- [ ] modify the relationship between the main clock and sub game
