### ISSUE TITLE
design: insert middle cutscene

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#12]
## What is this issue? 🚀
Create middle cutscene which shows the main story between Wand and Pu

## TODO 🏃‍♀️
- [x] Implement whole contexts on display 
- [x] Apply user interface
- [x] Add artworks for this cutscene
