### ISSUE TITLE
feat: implement first sorting game before main game

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#13]
## What is this issue? 🚀
Create sorting game that contains tiramisu cake and milk.

## TODO 🏃‍♀️
- [x] Make combo system
- [x] Implement clock
- [x] Create bonus and penalty policies for getting balloons
- [x] ~Apply artworks for tiramisu, milk, and so on~ **Postponed to finale artwork tasks**
- [x] Attain proper user interfaces
