### ISSUE TITLE
feat: implement main game

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#14]
## What is this issue? 🚀
Implement the main cafe tycoon game

## TODO 🏃‍♀️
- [x] Apply map design for cafe tycoon
- [x] Create a timer, satiety gauge, and Balloon gauge
- [x] Apply the prepaps of player, customers, and chef
- [x] Update Serving Capacity: 1 -> 2
- [x] Implement additional animation for player and customer

**Comment by YohanIm00** [comment]
Well Done!
