### ISSUE TITLE
docs: implement Project Proposal

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#19]
## What is this issue? 🚀
Create and modify the whole project proposal

## TODO 🏃‍♀️
- [x] Explain How to play
- [x] Describe the synopsis of the game
- [x] Attach some artworks
- [x] Add some reference of several open source repositories, etc.
- [x] Create both Korean and English README.md
