### ISSUE TITLE
modify: organize whole project

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#29]
## What is this issue? 🚀
Connect every scene and revise several details

## TODO 🏃‍♀️
- [x] Enhance SortingGame.cs
- [x] Modify ButtonManager.cs
- [x] Change sprites of Prologue scene
- [x] Update sprites and UI of Dialogue scene
- [x] Revise ending credits in GameClear scene
- [x] Set Audio sources for each methods
- [x] Connect every scene by SceneManager

**Comment by YohanIm00** [comment]
Well Done!
