### ISSUE TITLE
feat: implement player

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#3]
## What is this issue? 🚀
Make the main player and its actions.

## TODO 🏃‍♀️
- [x] Implement 4-direction movement
- [x] Make Player's Animations and Animator
- [x] ~Implement interactions with customers~ **This will be finished after Customer object is created**
- [x] Apply State Pattern to realize complicated action of Player
- [x] Use ScriptableObject to make object management easier
