### ISSUE TITLE
feat: implement customers

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#4]
## What is this issue? 🚀
Make customers and its tasks

## TODO 🏃‍♀️
- [x] Compose customer's animations
- [x] Add some interactions of customers
- [x] Set several actions: give balloons or pop it
- [x] Add there paths and apply it into prepaps
- [x] Add more sprites of additional cats
