### ISSUE TITLE
feat: implement chef

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#5]
## What is this issue? 🚀
make chef and add its additional animations

## TODO 🏃‍♀️
- [x] Make basis implementation of chef character: Pu
- [x] Add additional animations of chef
- [x] Implement several ScriptableObject: Menus, Emotions, etc.
