### ISSUE TITLE
chore: implement intro cutscene

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#6]
## What is this issue? 🚀
Implement intro cutscene and enhance it furthermore.

## TODO 🏃‍♀️
- [x] Use cinematic functions to realize intro
- [x] Implement tentative cutscene from the demo version
- [x] Create several C# source codes for controlling cutscene
- [x] Apply Dotween library to make fade-in transition.
- [x] ~Add additional sound effects~ **postponed for now**; this will be solved when I make Audio Manager
