### ISSUE TITLE
design: create main menu

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#7]
## What is this issue? 🚀
Create and design main menu and its buttons.

## TODO 🏃‍♀️
- [x] Create main menu
- [x] Add several buttons: Play, Setting, Exit
- [x] ~Apply new background music~ **postponed for now**; this will be solved when I make Audio Manager
