### ISSUE TITLE
design: complete map design

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#8]
## What is this issue? 🚀
Complete the map design of cafe in main game.

## TODO 🏃‍♀️
- [x] Make new pixel arts for applying cafe map
- [x] ~Make new pixel arts for applying town square map~ **Postponed to the trivial design tasks**
- [x] Apply tile map on the stage
