### ISSUE TITLE
design: complete whole art works on game

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS_DAWN#9]
## What is this issue? 🚀
Complete the whole artwork which can be used in game.

## TODO 🏃‍♀️
- [x] Concept art for Main Characters: Wand, Pu
- [x] Background image of main menu
- [x] Game over image
- [x] Game clear image
- [x] Face chips of main characters: Wand, PU
- [x] Logo images
- [x] User Interfaces: Clock, Receipts, Balloon gauge, etc.
- [x] Some pixel arts
- [x] Artworks for middle-cutscene
- [x] Art assets for first classification game

**Comment by YohanIm00** [comment]
Thanks a million, PZJB👍🏼
